name: Code Guide by @mdo
description: Estándares para desarrollar HTML y CSS consistentes, flexibles y sostenibles.
url: https://codeguide.co
permalink: pretty
sass:
  style: compressed
version: 4.0.0
og_image: https://raw.githubusercontent.com/mdo/code-guide/gh-pages/code-guide-social.png
